version: "3"

services:
  nginx:
    build: ./nginx/
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=billshare.com.br,www.billshare.com.br
  app:
    build: .
    command: yarn start
networks:
  default:
    external:
      name: nginx-proxy
