version: "3"

services:
  app:
    build: .
    command: yarn start
    environment:
      - VIRTUAL_HOST=billshare.com.br,www.billshare.com.br
    expose:
      - 80
networks:
  default:
    external:
      name: nginx-proxy
