version: "3"

services:
  nginx:
    image: nginx:latest
    networks:
      - nginx-proxy
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=billshare.com.br,www.billshare.com.br
  app:
    build: .
    command: yarn start
    networks:
      - nginx-proxy
    expose:
      - 3000
networks:
  default:
    external:
      name: nginx-proxy
